apiVersion: v1
kind: Service
metadata:
  name: vue-frontend-service
  namespace: frontend
spec:
  type: NodePort
  ports:
  - port: 80       # Port inside the cluster
    targetPort: 80  # Port that your container is listening on
    nodePort: 30907   # Port exposed on the node (can be any port within the range 30000-32767)
  selector:
    app: vue-frontend
    